server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i8d107.p.ssafy.io:3311/speakon-dev
    username: hamchu
    password: dlgmltn0114

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9fb0d419b0f00382d15ca48e0790d6dc
            client-secret: JQWEMoFIaR7gzISTYouaB8LqVK2O0Bta
            redirect-uri: http://i8d107.p.ssafy.io:8811/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  activemq:
    broker-url:

file:
  dir: C:\test\
#  dir: /usr/app/speakon-dev/

app:
  oauth2:
    authorizedRedirectUri: "http://localhost:3000/auth" # 임시

jwt:
  secret: godheesu
  issuer: speakon

openvidu:
  OPENVIDU_URL: https://i8d107.p.ssafy.io:443/
  OPENVIDU_SECRET: MY_SECRET
