server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://hamchu-dev.shop:3311/security
    username: hamchu
    password: dlgmltn0114

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true