server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://hamchu-dev.shop:3311/security
    username: hamchu
    password: dlgmltn0114

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9fb0d419b0f00382d15ca48e0790d6dc
            client-secret: JQWEMoFIaR7gzISTYouaB8LqVK2O0Bta
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  oauth2:
    authorizedRedirectUri: "http://localhost:3000" # 임시

jwt:
  secret: godheesu
  issuer: speakon